// Products Data
const products = [
    // Kitchen Products
    {
        id: 1,
        name: "Non-Stick Cookware Set",
        brand: "Prestige",
        category: "kitchen",
        subcategory: "cookware",
        price: 2499,
        originalPrice: 3999,
        discount: 38,
        rating: 4.3,
        reviewCount: 1247,
        image: "https://images.pexels.com/photos/4226796/pexels-photo-4226796.jpeg?auto=compress&cs=tinysrgb&w=400",
        badge: "Bestseller",
        gst: 18
    },
    {
        id: 2,
        name: "Stainless Steel Pressure Cooker",
        brand: "Hawkins",
        category: "kitchen",
        subcategory: "cookware",
        price: 1899,
        originalPrice: 2499,
        discount: 24,
        rating: 4.5,
        reviewCount: 892,
        image: "https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg?auto=compress&cs=tinysrgb&w=400",
        gst: 18
    },
    {
        id: 3,
        name: "Electric Rice Cooker",
        brand: "Panasonic",
        category: "kitchen",
        subcategory: "appliances",
        price: 3299,
        originalPrice: 4199,
        discount: 21,
        rating: 4.2,
        reviewCount: 634,
        image: "https://images.pexels.com/photos/4226796/pexels-photo-4226796.jpeg?auto=compress&cs=tinysrgb&w=400",
        gst: 18
    },
    {
        id: 4,
        name: "Knife Set with Block",
        brand: "Victorinox",
        category: "kitchen",
        subcategory: "cutlery",
        price: 4599,
        originalPrice: 5999,
        discount: 23,
        rating: 4.6,
        reviewCount: 445,
        image: "https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg?auto=compress&cs=tinysrgb&w=400",
        badge: "Premium",
        gst: 18
    },
    {
        id: 5,
        name: "Microwave Oven",
        brand: "LG",
        category: "kitchen",
        subcategory: "appliances",
        price: 8999,
        originalPrice: 12999,
        discount: 31,
        rating: 4.4,
        reviewCount: 789,
        image: "https://images.pexels.com/photos/4226796/pexels-photo-4226796.jpeg?auto=compress&cs=tinysrgb&w=400",
        gst: 18
    },
    {
        id: 6,
        name: "Ceramic Dinner Set",
        brand: "Corelle",
        category: "kitchen",
        subcategory: "dinnerware",
        price: 2799,
        originalPrice: 3599,
        discount: 22,
        rating: 4.1,
        reviewCount: 567,
        image: "https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg?auto=compress&cs=tinysrgb&w=400",
        gst: 18
    },

    // Decor Products
    {
        id: 7,
        name: "Modern Wall Art Canvas",
        brand: "ArtVibe",
        category: "decor",
        subcategory: "wall-art",
        price: 1299,
        originalPrice: 1899,
        discount: 32,
        rating: 4.3,
        reviewCount: 234,
        image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=400",
        badge: "Trending",
        gst: 18
    },
    {
        id: 8,
        name: "Decorative Table Lamp",
        brand: "Philips",
        category: "lighting",
        subcategory: "table-lamps",
        price: 2199,
        originalPrice: 2999,
        discount: 27,
        rating: 4.4,
        reviewCount: 456,
        image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=400",
        gst: 18
    },
    {
        id: 9,
        name: "Ceramic Vase Set",
        brand: "HomeDecor",
        category: "decor",
        subcategory: "vases",
        price: 899,
        originalPrice: 1299,
        discount: 31,
        rating: 4.2,
        reviewCount: 189,
        image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=400",
        gst: 18
    },
    {
        id: 10,
        name: "LED Ceiling Light",
        brand: "Syska",
        category: "lighting",
        subcategory: "ceiling-lights",
        price: 3499,
        originalPrice: 4599,
        discount: 24,
        rating: 4.5,
        reviewCount: 678,
        image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=400",
        badge: "Energy Efficient",
        gst: 18
    },
    {
        id: 11,
        name: "Wooden Photo Frame Set",
        brand: "CraftVilla",
        category: "decor",
        subcategory: "frames",
        price: 799,
        originalPrice: 1199,
        discount: 33,
        rating: 4.1,
        reviewCount: 123,
        image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=400",
        gst: 18
    },
    {
        id: 12,
        name: "Decorative Mirror",
        brand: "ReflectHome",
        category: "decor",
        subcategory: "mirrors",
        price: 1599,
        originalPrice: 2199,
        discount: 27,
        rating: 4.3,
        reviewCount: 345,
        image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=400",
        gst: 18
    },

    // Additional Kitchen Products
    {
        id: 13,
        name: "Blender & Juicer Combo",
        brand: "Preethi",
        category: "kitchen",
        subcategory: "appliances",
        price: 5499,
        originalPrice: 7299,
        discount: 25,
        rating: 4.3,
        reviewCount: 567,
        image: "https://images.pexels.com/photos/4226796/pexels-photo-4226796.jpeg?auto=compress&cs=tinysrgb&w=400",
        gst: 18
    },
    {
        id: 14,
        name: "Cast Iron Skillet",
        brand: "Lodge",
        category: "kitchen",
        subcategory: "cookware",
        price: 1899,
        originalPrice: 2499,
        discount: 24,
        rating: 4.6,
        reviewCount: 234,
        image: "https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg?auto=compress&cs=tinysrgb&w=400",
        badge: "Chef's Choice",
        gst: 18
    },
    {
        id: 15,
        name: "Glass Storage Containers",
        brand: "Borosil",
        category: "kitchen",
        subcategory: "storage",
        price: 1299,
        originalPrice: 1799,
        discount: 28,
        rating: 4.4,
        reviewCount: 456,
        image: "https://images.pexels.com/photos/4226796/pexels-photo-4226796.jpeg?auto=compress&cs=tinysrgb&w=400",
        gst: 18
    },

    // Additional Decor Products
    {
        id: 16,
        name: "Hanging Planters Set",
        brand: "GreenSpace",
        category: "decor",
        subcategory: "planters",
        price: 999,
        originalPrice: 1399,
        discount: 29,
        rating: 4.2,
        reviewCount: 178,
        image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=400",
        gst: 18
    },
    {
        id: 17,
        name: "Pendant Light Fixture",
        brand: "Havells",
        category: "lighting",
        subcategory: "pendant-lights",
        price: 2799,
        originalPrice: 3699,
        discount: 24,
        rating: 4.5,
        reviewCount: 389,
        image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=400",
        badge: "Designer",
        gst: 18
    },
    {
        id: 18,
        name: "Decorative Cushion Covers",
        brand: "FabIndia",
        category: "decor",
        subcategory: "textiles",
        price: 599,
        originalPrice: 899,
        discount: 33,
        rating: 4.1,
        reviewCount: 267,
        image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=400",
        gst: 18
    }
];
