// Product Data - Myntra Style
const products = [
    // Home Category - Smart Home Products
    {
        id: 1,
        name: "Smart Bluetooth Speaker with Voice Assistant",
        brand: "TechHome",
        category: "home",
        subcategory: "electronics",
        price: 4799,
        originalPrice: 5999,
        gst: 18,
        discount: 20,
        rating: 4.3,
        reviewCount: 1247,
        image: "https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg",
        description: "Premium sound quality with voice assistant and wireless connectivity",
        badge: "BESTSELLER"
    },
    {
        id: 2,
        name: "LED Ambient Smart Lamp with App Control",
        brand: "LightCraft",
        category: "home",
        subcategory: "lighting",
        price: 2999,
        originalPrice: 3999,
        gst: 12,
        discount: 25,
        rating: 4.5,
        reviewCount: 892,
        image: "https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg",
        description: "Color-changing LED lamp with remote control and app connectivity"
    },
    {
        id: 3,
        name: "Wireless Fast Charging Pad - 15W",
        brand: "PowerTech",
        category: "home",
        subcategory: "electronics",
        price: 2299,
        originalPrice: 2899,
        gst: 18,
        discount: 21,
        rating: 4.2,
        reviewCount: 634,
        image: "https://images.pexels.com/photos/4138932/pexels-photo-4138932.jpeg",
        description: "Fast wireless charging for all compatible devices"
    },
    {
        id: 4,
        name: "Designer Neon Wall Clock - Customizable",
        brand: "ModernTime",
        category: "home",
        subcategory: "decor",
        price: 3999,
        originalPrice: 4999,
        gst: 12,
        discount: 20,
        rating: 4.4,
        reviewCount: 456,
        image: "https://images.pexels.com/photos/1170412/pexels-photo-1170412.jpeg",
        description: "Modern neon clock with customizable colors and silent movement"
    },
    {
        id: 5,
        name: "Ergonomic Office Chair - Premium Mesh",
        brand: "ComfortZone",
        category: "furniture",
        subcategory: "chairs",
        price: 15999,
        originalPrice: 19999,
        gst: 18,
        discount: 20,
        rating: 4.6,
        reviewCount: 1123,
        image: "https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg",
        description: "Premium ergonomic chair with lumbar support and breathable mesh",
        badge: "PREMIUM"
    },
    {
        id: 6,
        name: "Smart Home Hub - Voice Control Center",
        brand: "SmartLiving",
        category: "home",
        subcategory: "electronics",
        price: 6799,
        originalPrice: 7999,
        gst: 18,
        discount: 15,
        rating: 4.3,
        reviewCount: 789,
        image: "https://images.pexels.com/photos/4112236/pexels-photo-4112236.jpeg",
        description: "Central hub to control all your smart home devices"
    },

    // Kitchen Category
    {
        id: 7,
        name: "Premium Non-Stick Cookware Set - 7 Pieces",
        brand: "ChefMaster",
        category: "kitchen",
        subcategory: "cookware",
        price: 10999,
        originalPrice: 13999,
        gst: 12,
        discount: 21,
        rating: 4.5,
        reviewCount: 2134,
        image: "https://images.pexels.com/photos/1599791/pexels-photo-1599791.jpeg",
        description: "Non-stick cookware set with induction base and glass lids",
        badge: "BESTSELLER"
    },
    {
        id: 8,
        name: "High-Speed Blender - 1200W Motor",
        brand: "BlendPro",
        category: "kitchen",
        subcategory: "appliances",
        price: 5599,
        originalPrice: 6999,
        gst: 12,
        discount: 20,
        rating: 4.4,
        reviewCount: 1567,
        image: "https://images.pexels.com/photos/6544378/pexels-photo-6544378.jpeg",
        description: "Professional-grade blender with multiple speed settings"
    },
    {
        id: 9,
        name: "Portable Induction Cooktop - Touch Control",
        brand: "CookSmart",
        category: "kitchen",
        subcategory: "appliances",
        price: 3999,
        originalPrice: 4999,
        gst: 12,
        discount: 20,
        rating: 4.2,
        reviewCount: 987,
        image: "https://images.pexels.com/photos/4226796/pexels-photo-4226796.jpeg",
        description: "Energy-efficient induction cooktop with touch controls"
    },
    {
        id: 10,
        name: "Smart Electric Kettle - Temperature Control",
        brand: "BrewMaster",
        category: "kitchen",
        subcategory: "appliances",
        price: 3399,
        originalPrice: 3999,
        gst: 12,
        discount: 15,
        rating: 4.3,
        reviewCount: 743,
        image: "https://images.pexels.com/photos/6492397/pexels-photo-6492397.jpeg",
        description: "Temperature-controlled kettle with app connectivity"
    },
    {
        id: 11,
        name: "Professional Chef Knife Set - German Steel",
        brand: "SharpEdge",
        category: "kitchen",
        subcategory: "cutlery",
        price: 4399,
        originalPrice: 5499,
        gst: 12,
        discount: 20,
        rating: 4.6,
        reviewCount: 1234,
        image: "https://images.pexels.com/photos/4226900/pexels-photo-4226900.jpeg",
        description: "Sharp stainless steel knives with wooden block"
    },
    {
        id: 12,
        name: "Multi-Function Food Processor - 12 Attachments",
        brand: "KitchenPro",
        category: "kitchen",
        subcategory: "appliances",
        price: 8999,
        originalPrice: 10999,
        gst: 12,
        discount: 18,
        rating: 4.4,
        reviewCount: 892,
        image: "https://images.pexels.com/photos/4226796/pexels-photo-4226796.jpeg",
        description: "Versatile food processor with multiple attachments"
    },

    // Décor Category
    {
        id: 13,
        name: "Abstract Canvas Art - Modern Collection",
        brand: "ArtStudio",
        category: "decor",
        subcategory: "wall-art",
        price: 5999,
        originalPrice: 7999,
        gst: 12,
        discount: 25,
        rating: 4.5,
        reviewCount: 567,
        image: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
        description: "Modern abstract painting on premium canvas"
    },
    {
        id: 14,
        name: "Handcrafted Ceramic Sculpture - Contemporary",
        brand: "CraftHouse",
        category: "decor",
        subcategory: "sculptures",
        price: 3999,
        originalPrice: 4999,
        gst: 12,
        discount: 20,
        rating: 4.3,
        reviewCount: 234,
        image: "https://images.pexels.com/photos/6195104/pexels-photo-6195104.jpeg",
        description: "Handcrafted ceramic sculpture for modern interiors"
    },
    {
        id: 15,
        name: "Designer Floor Lamp - Adjustable Brightness",
        brand: "LuxLight",
        category: "lighting",
        subcategory: "floor-lamps",
        price: 9999,
        originalPrice: 12999,
        gst: 18,
        discount: 23,
        rating: 4.6,
        reviewCount: 445,
        image: "https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg",
        description: "Contemporary floor lamp with adjustable brightness",
        badge: "PREMIUM"
    },
    {
        id: 16,
        name: "Decorative Ceramic Vase - Textured Finish",
        brand: "HomeDecor",
        category: "decor",
        subcategory: "vases",
        price: 2299,
        originalPrice: 2899,
        gst: 12,
        discount: 21,
        rating: 4.2,
        reviewCount: 178,
        image: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
        description: "Elegant ceramic vase with unique texture"
    },
    {
        id: 17,
        name: "Luxury Area Rug - Persian Design",
        brand: "RugCraft",
        category: "decor",
        subcategory: "textiles",
        price: 12999,
        originalPrice: 15999,
        gst: 12,
        discount: 19,
        rating: 4.7,
        reviewCount: 334,
        image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg",
        description: "Premium wool rug with intricate patterns",
        badge: "LUXURY"
    },
    {
        id: 18,
        name: "Wooden Photo Frame Set - Vintage Style",
        brand: "FrameArt",
        category: "decor",
        subcategory: "wall-art",
        price: 1999,
        originalPrice: 2499,
        gst: 12,
        discount: 20,
        rating: 4.1,
        reviewCount: 267,
        image: "https://images.pexels.com/photos/1090638/pexels-photo-1090638.jpeg",
        description: "Set of wooden frames in various sizes"
    },

    // Additional Products
    {
        id: 19,
        name: "Stainless Steel Pressure Cooker - 5L",
        brand: "CookWell",
        category: "kitchen",
        subcategory: "cookware",
        price: 5199,
        originalPrice: 6499,
        gst: 12,
        discount: 20,
        rating: 4.4,
        reviewCount: 1456,
        image: "https://images.pexels.com/photos/4226796/pexels-photo-4226796.jpeg",
        description: "Heavy-duty pressure cooker with safety features"
    },
    {
        id: 20,
        name: "Digital Kitchen Scale - Precision Weighing",
        brand: "AccuWeigh",
        category: "kitchen",
        subcategory: "appliances",
        price: 1899,
        originalPrice: 2299,
        gst: 18,
        discount: 17,
        rating: 4.2,
        reviewCount: 523,
        image: "https://images.pexels.com/photos/6492397/pexels-photo-6492397.jpeg",
        description: "Precision digital scale for accurate measurements"
    },
    {
        id: 21,
        name: "Vintage Wall Mirror - Ornate Frame",
        brand: "MirrorCraft",
        category: "decor",
        subcategory: "wall-art",
        price: 6799,
        originalPrice: 8499,
        gst: 12,
        discount: 20,
        rating: 4.5,
        reviewCount: 289,
        image: "https://images.pexels.com/photos/1090638/pexels-photo-1090638.jpeg",
        description: "Ornate vintage-style mirror with decorative frame"
    },
    {
        id: 22,
        name: "Crystal Table Lamp - Elegant Design",
        brand: "CrystalLux",
        category: "lighting",
        subcategory: "table-lamps",
        price: 8299,
        originalPrice: 9999,
        gst: 18,
        discount: 17,
        rating: 4.6,
        reviewCount: 367,
        image: "https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg",
        description: "Elegant crystal table lamp with fabric shade"
    },
    {
        id: 23,
        name: "Marble Bookends - Geometric Design",
        brand: "StoneArt",
        category: "decor",
        subcategory: "sculptures",
        price: 3499,
        originalPrice: 4299,
        gst: 12,
        discount: 19,
        rating: 4.3,
        reviewCount: 156,
        image: "https://images.pexels.com/photos/6195104/pexels-photo-6195104.jpeg",
        description: "Handcrafted marble bookends with geometric design"
    },
    {
        id: 24,
        name: "Silk Throw Pillows - Set of 2",
        brand: "SilkTouch",
        category: "decor",
        subcategory: "textiles",
        price: 4399,
        originalPrice: 5499,
        gst: 12,
        discount: 20,
        rating: 4.4,
        reviewCount: 445,
        image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg",
        description: "Luxurious silk throw pillows in vibrant colors"
    },
    {
        id: 25,
        name: "Smart Storage Ottoman - Hidden Compartment",
        brand: "SmartStore",
        category: "furniture",
        subcategory: "storage",
        price: 7999,
        originalPrice: 9999,
        gst: 18,
        discount: 20,
        rating: 4.3,
        reviewCount: 234,
        image: "https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg",
        description: "Multi-functional ottoman with hidden storage"
    },
    {
        id: 26,
        name: "LED Strip Lights - Smart RGB",
        brand: "ColorLight",
        category: "lighting",
        subcategory: "led-lights",
        price: 2799,
        originalPrice: 3499,
        gst: 18,
        discount: 20,
        rating: 4.2,
        reviewCount: 678,
        image: "https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg",
        description: "Smart RGB LED strips with app control"
    }
];

// Export products for use in main.js
window.products = products;
